### ISSUE TITLE
Stable Rust prospects?

### ISSUE THREAD

**Issue by dvtomas** [gnzlbg/slice_deque#34]
The library looks quite nice. Is there a chance it could work on stable rust in near future?

**Comment by gnzlbg** [comment]
It does work on stable Rust: https://travis-ci.org/gnzlbg/slice_deque/jobs/351930244 ?

**Comment by dvtomas** [comment]
Hmm, I must be doing something wrong.

I put a `slice-deque = "0"` into `Cargo.toml` dependencies.

`extern crate slice_deque;` in `main.rs`

I get these errors on compilation:

```
   Compiling slice-deque v0.1.5
error[E0433]: failed to resolve. Could not find `NonNull` in `ptr`
    --> /home/td/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.5/src/lib.rs:2230:27
     |
2230 |                 buf: ptr::NonNull::new_unchecked(buf_ptr),
     |                           ^^^^^^^ Could not find `NonNull` in `ptr`

error[E0412]: cannot find type `NonNull` in module `ptr`
    --> /home/td/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.5/src/lib.rs:1920:15
     |
1920 |     deq: ptr::NonNull<SliceDeque<T>>,
     |               ^^^^^^^ not found in `ptr`

error[E0412]: cannot find type `NonNull` in module `ptr`
    --> /home/td/.cargo/registry/src/github.com-1ecc6299db9ec823/slice-deque-0.1.5/src/lib.rs:1997:15
     |
1997 |     buf: ptr::NonNull<T>,
     |               ^^^^^^^ not found in `ptr`
```

I'm using rust 1.24.0

**Comment by gnzlbg** [comment]
Could you try with master? Putting:

```toml
[dependency.slice_deque]
git = "https://github.com/gnzlbg/slice_deque"
```

should do the trick. Maybe the works on stable features are not part of the latest release.

**Comment by dvtomas** [comment]
Yeah, that works! (the exact lines are
```
[dependencies.slice-deque]
git = "https://github.com/gnzlbg/slice_deque"
```
)

You fulfill my wishes before I make them, thank you :)

**Comment by gnzlbg** [comment]
So I'll let you know here when I do a new release, so that you can stop using the `git = ..` hack. 

Basically what's holding a new release is doing a new release on `mach` first, and that's on hold until https://github.com/rust-lang/rust/pull/48528 is merged :/

**Comment by dvtomas** [comment]
OK, thank you so much.
