### ISSUE TITLE
Drain iterator is unstable

### ISSUE THREAD

**Issue by luben** [gnzlbg/slice_deque#63]
Hi,

It surprised me that the `drain` method requires unstable. Have it checked locally with only this change and it works for me (rust-1.33). Is there a reason `drain` to require unstable?

**Comment by gnzlbg** [comment]
This was probably because of the trusted len / exact size impls, but I agree that this should not be necessary, stable drain would just perform worse than the unstable one, but that's ok.

**Comment by luben** [comment]
My guess is it's because ops::RangeBounds were stabilized recently in Rust-1.28.
